### PR TITLE
Get language

### PR DESCRIPTION
**Pull request by edreamleo**
Adds bc.getLanguageFromPosition.

See the comments in the code a choice of what should be returned.

### CODE REVIEW

**Comment by edreamleo** [comment]
Drat. The diff isn't what I want.  I'll close this issue and wait until you merge #89.

**Comment by boltex** [comment]
I merged it and pushed back to dev, pull it onto your machine to see the
little (one word or two) changes / cleanup I did... And fix anything you
might have forgotten or want to change :)
--
Félix

**Comment by boltex** [comment]
Maybe Ill remove all that's flooding the terminal output with all 900
function names lol , (and many single 'f' too, is it normal?)

**Comment by boltex** [comment]
All right, going to bed earlier now!

I removed 12 out of the 24 extraneous methods in the server. (gotta pass
the p_keepselection parameter from vscode instead to get rid of the other
12)

I'll do that tomorrow before switching to the syntax / coloring .

--
Félix

**Comment by edreamleo** [comment]
On Wed, Jul 22, 2020 at 10:12 PM Felix <notifications@github.com> wrote:

> All right, going to bed earlier now!
>

Good idea. Sleep is underrated. It's extremely important!

I removed 12 out of the 24 extraneous methods in the server. (gotta pass
> the p_keepselection parameter from vscode instead to get rid of the other
> 12)
>
> I'll do that tomorrow before switching to the syntax / coloring .
>

Thanks for the update. I'll create one or two leoInteg issues explaining my
plans for the next day or so.

Edward

**Comment by edreamleo** [comment]
On Wed, Jul 22, 2020 at 8:39 PM Felix <notifications@github.com> wrote:

> I merged it and pushed back to dev, pull it onto your machine to see the
> little (one word or two) changes / cleanup I did... And fix anything you
> might have forgotten or want to change :)
>

Looks good to me.

I have just created leoInteg #92
<https://github.com/boltex/leointeg/issues/92>, remove Leo commands that
don't make sense in leoInteg. The "commands" branch will contain the work.

I made a mistake yesterday by not creating a separate branch for
bc.getLanguageAtPosition. As a result, that work got merged into the
previous PR. Live and learn...

Edward

**Comment by edreamleo** [comment]
On Wed, Jul 22, 2020 at 8:41 PM Felix <notifications@github.com> wrote:

> Maybe Ill remove all that's flooding the terminal output with all 900
> function names lol , (and many single 'f' too, is it normal?)
>

I see you removed the trace. I should have done that.

I don't recall seeing single 'f' commands. I'll investigate as part of leoInteg
#92. <https://github.com/boltex/leointeg/issues/92>

Edward

**Pull request closed without merging**
